spring.application.name=cin-news-links

# Endpoint de autenticação do token keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri: http://localhost:8088/realms/dsv
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.client-id=cin
spring.security.oauth2.client.registration.keycloak.client-name=cin
spring.security.oauth2.client.registration.keycloak.client-secret=fcpfsdjrfPOx16bCweABCGnXzdxeV0aJ
spring.security.oauth2.client.registration.keycloak.scope: openid, offline_access, profile


security.success-url: http://localhost:8080/
security.logout-url: http://localhost:8088/realms/dsv/protocol/openid-connect/logout
security.redirect-uri: http://localhost:8080/


spring.datasource.url=jdbc:h2:mem:hotlink
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

#THYMELEAF
spring.thymeleaf.cache=false