-- insert into tb01_link (titulo,endereco) values ('','');

insert into tb01_link (titulo,endereco) values ('Carteira de Identidade Nacional CIN','https://www.gov.br/governodigital/pt-br/identidade/identificacao-do-cidadao-e-carteira-de-identidade-nacional/carteira-de-identidade-nacional-cin-1');
insert into tb01_link (titulo,endereco) values ('Obter Carteira de Identidade Nacional | MG.GOV.BR','https://www.mg.gov.br/servico/obter-carteira-de-identidade-nacional');
insert into tb01_link (titulo,endereco) values ('OBTER 1ª VIA DA CARTEIRA DE IDENTIDADE NACIONAL','https://www.ba.gov.br/servico/dpt/obter-1-via-da-carteira-de-identidade-nacional-cin');
insert into tb01_link (titulo,endereco) values ('Obter Carteira de Identidade Nacional - CIN','https://www.poupatempo.sp.gov.br/carta/D97C3844-A2D9-4C9E-B364-CB4FEB26A1FB');
insert into tb01_link (titulo,endereco) values ('INFORMAÇÕES SOBRE A CARTEIRA DE IDENTIDADE NACIONAL (CIN)','https://www.policiacivil.pr.gov.br/Pagina/INFORMACOES-SOBRE-CARTEIRA-DE-IDENTIDADE-NACIONAL-CIN');
insert into tb01_link (titulo,endereco) values ('Dez milhões de brasileiros têm a nova Carteira de Identidade Nacional','https://agenciabrasil.ebc.com.br/geral/noticia/2024-07/dez-milhoes-de-brasileiros-tem-nova-carteira-de-identidade-nacional');
insert into tb01_link (titulo,endereco) values ('Carteira Nacional de Identidade: Detran RJ começa a emitir documento para substituir RG; saiba como tirar','https://g1.globo.com/rj/rio-de-janeiro/noticia/2024/07/02/carteira-nacional-de-identidade-detran-rj-comeca-a-emitir-documento-para-substituir-rg-saiba-como-tirar.ghtml');
insert into tb01_link (titulo,endereco) values ('Nova Carteira de Identidade Nacional possibilita melhoria dos serviços públicos','https://agenciagov.ebc.com.br/noticias/202410/nova-carteira-de-identidade-nacional-possibilita-melhoria-dos-servicos-publicos');
insert into tb01_link (titulo,endereco) values ('Solicite o agendamento da emissão da sua Carteira de Identidade Nacional (CIN)','https://agendamentorg.portaldacidadania.pb.gov.br');
insert into tb01_link (titulo,endereco) values ('CARTEIRA DE IDENTIDADE NACIONAL - CIN (FORMATO FÍSICO E DIGITAL)','https://portaldocidadao.ro.gov.br/Servico/Detalhes?id=6519034e-f310-4cbb-3d7d-08da1e5c6341');
insert into tb01_link (titulo,endereco) values ('Paraná passa a emitir a nova Carteira de Identidade Nacional','https://www.aen.pr.gov.br/Noticia/Parana-passa-emitir-nova-Carteira-de-Identidade-Nacional');
insert into tb01_link (titulo,endereco) values ('SP substitui emissão da primeira via do RG pela Carteira de Identidade Nacional','https://www.saopaulo.sp.gov.br/spnoticias/ultimas-noticias/sp-substitui-emissao-da-primeira-via-do-rg-pela-carteira-de-identidade-nacional/');
insert into tb01_link (titulo,endereco) values ('Estado do RJ passa a emitir nova Carteira de Identidade para pessoas de todas as idades nesta terça','https://exame.com/brasil/detran-rj-comeca-emitir-nova-carteira-identificacao-nacional/');
insert into tb01_link (titulo,endereco) values ('Carteira de Identidade Nacional (CIN)','https://www.sc.gov.br/servicos/emitir-carteira-de-identidade');
insert into tb01_link (titulo,endereco) values ('agendamento para emissão da carteira de identidade nacional - cin - pca - PCA','https://apdigital.portal.ap.gov.br/servico/solicitacao-de-agendamento-para-emissao-da-1o-via-da-carteira-de-identidade-nacional-cin1');
insert into tb01_link (titulo,endereco) values ('Orientações para emissão da Nova Carteira de Identidade Nacional – CIN','https://www.ssp.am.gov.br/orientacoes-para-emissao-da-nova-carteira-de-identidade-nacional/');
insert into tb01_link (titulo,endereco) values ('Quem tiver a nova carteira de identidade recebe excelente notícia','https://tribunademinas.com.br/colunas/maistendencias/quem-tiver-a-nova-carteira-de-identidade-recebe-excelente-noticia/');
insert into tb01_link (titulo,endereco) values ('Prefeitura retoma atendimento para emissão da Carteira de Identidade Nacional exclusiva para maracanauenses','https://www.maracanau.ce.gov.br/prefeitura-retoma-atendimento-para-emissao-da-carteira-de-identidade-nacional-exclusiva-para-maracanauenses/');
insert into tb01_link (titulo,endereco) values ('Nova Carteira de Identidade Nacional traz mais segurança para suas informações; confira','https://fdr.com.br/2025/02/27/nova-carteira-de-identidade-nacional-traz-mais-seguranca-para-suas-informacoes-confira/amp/');
insert into tb01_link (titulo,endereco) values ('Perdeu o RG? Veja como emitir uma nova via de forma totalmente digital e gratuita','https://fdr.com.br/2025/02/28/perdeu-o-rg-veja-como-emitir-uma-nova-via-de-forma-totalmente-digital-e-gratuita/amp/');
insert into tb01_link (titulo,endereco) values ('Mais de 20 milhões de brasileiros já possuem a nova carteira de identidade','https://noticias.r7.com/cidades/mais-de-20-milhoes-de-brasileiros-ja-possuem-a-nova-carteira-de-identidade-10022025/');
insert into tb01_link (titulo,endereco) values ('Últimos dias para pedir novo RG e receber ainda neste mês','https://fdr.com.br/2025/02/09/ultimos-dias-para-pedir-novo-rg-e-receber-ainda-neste-mes/');
insert into tb01_link (titulo,endereco) values ('MUTIRÃO da Nova Carteira de Identidade começa nesta terça-feira (11) – Quais os horários de atendimento?','https://obolsafamiliabrasil.com.br/2025/02/10/mutirao-da-nova-carteira-de-identidade-comeca-nesta-terca-feira-11-quais-os-horarios-de-atendimento/');
insert into tb01_link (titulo,endereco) values ('CIN obrigatória: saiba como emitir e o que muda na sua identificação','https://www.gazetadopovo.com.br/brasil/cin-obrigatoria-saiba-como-emitir-e-o-que-muda-na-sua-identificacao/');
insert into tb01_link (titulo,endereco) values ('Antigo RG está com os dias contados: veja como emitir a Nova Carteira de Identidade agora mesmo','https://ndmais.com.br/justica/antigo-rg-esta-com-os-dias-contados-veja-como-emitir-a-nova-carteira-de-identidade-agora-mesmo/');
insert into tb01_link (titulo,endereco) values ('Perdi o RG, e agora? Saiba como tirar a segunda via de graça com apenas 1 documento','https://ndmais.com.br/cidadania/como-tirar-a-segunda-via-do-rg-sem-pagar/');
insert into tb01_link (titulo,endereco) values ('Nova Carteira de Identidade: mutirão de atualização de documentos será na próxima segunda (10)','https://www.pensarcursos.com.br/blog/nova-carteira-de-identidade-mutirao-de-atualizacao-de-documentos-sera-na-proxima-segunda-10/ ');
insert into tb01_link (titulo,endereco) values ('Feira oferece encaminhamentos para emissão gratuita de carteiras de identidade','https://www.correio24horas.com.br/bahia/feira-oferece-encaminhamentos-para-emissao-gratuita-de-carteiras-de-identidade-1125 ');
insert into tb01_link (titulo,endereco) values ('Nova Carteira de Identidade: atendimento exclusivo neste sábado (08) para idosos','https://noticiasconcursos.com.br/nova-carteira-de-identidade-atendimento-exclusivo-neste-sabado-08-para-idosos/ ');
insert into tb01_link (titulo,endereco) values ('RG mais fácil em SC: agora é possível solicitar a carteira de identidade sem sair de casa','https://ndmais.com.br/cidadania/rg-mais-facil-em-sc-agora-e-possivel-solicitar-a-carteira-de-identidade-sem-sair-de-casa/ ');
insert into tb01_link (titulo,endereco) values ('Carteira de identidade: documento será emitido em até 15 dias no ES em 2026','https://www.agazeta.com.br/es/cotidiano/carteira-de-identidade-documento-sera-emitido-em-ate-15-dias-no-es-em-2026-1025 ');
insert into tb01_link (titulo,endereco) values ('RG tradicional valerá até quando? Saiba prazo limite e como emitir nova CIN','https://economia.uol.com.br/noticias/redacao/2025/10/29/nova-cin-substitui-rg-e-cpf-entenda-prazos-e-como-emitir-o-documento.htm');
insert into tb01_link (titulo,endereco) values ('Endereço do site de agendamento da Carteira de Identidade Nacional é alterado','https://agorarn.com.br/ultimas/site-carteira-de-identidade-alterado/');
insert into tb01_link (titulo,endereco) values ('Nova Carteira de Identidade: saiba o prazo máximo para renovar, como emitir RG e quanto custa','https://ndmais.com.br/cidadania/nova-carteira-de-identidade-saiba-como-e-quando-renovar/');
insert into tb01_link (titulo,endereco) values ('Nova Carteira de Identidade: SAC realiza mutirão para crianças e adolescentes de até 17 anos neste sábado (11)','https://noticiasconcursos.com.br/nova-carteira-de-identidade-sac-realiza-mutirao-para-criancas-e-adolescentes-de-ate-17-anos-neste-sabado-11/');
insert into tb01_link (titulo,endereco) values ('Quase 1 milhão de potiguares já têm a nova Carteira de Identidade Nacional; veja como emitir','https://www.grandeponto.com.br/noticia/quase-1-milhao-de-potiguares-ja-tem-a-nova-carteira-de-identidade-nacional-veja-como-emitir');
insert into tb01_link (titulo,endereco) values ('Mutirão para emissão gratuita da nova Carteira de Identidade será realizado de 1º a 3/10','https://noticiasconcursos.com.br/mutirao-para-emissao-gratuita-da-nova-carteira-de-identidade-sera-realizado-de-1o-a-3-10/');
insert into tb01_link (titulo,endereco) values ('Quanto custa tirar a primeira via do novo RG, o CIN?','https://n1n.com.br/beneficios/quanto-custa-tirar-a-primeira-via-do-novo-rg-o-cin/');
insert into tb01_link (titulo,endereco) values ('Como fazer o novo RG (CIN) em formato cartão?','https://n1n.com.br/beneficios/como-fazer-o-novo-rg-cin-em-formato-cartao/');
insert into tb01_link (titulo,endereco) values ('RG antigo precisa ser trocado pela CIN se ele estiver nessas 5 condições','https://n1n.com.br/beneficios/rg-antigo-precisa-ser-trocado-pela-cin-se-ele-estiver-nessas-5-condicoes/');
insert into tb01_link (titulo,endereco) values ('Brasileiros têm até 2032 para substituir o RG antigo pelo novo CIN e garantir os benefícios','https://n1n.com.br/noticias-gerais/brasileiros-tem-ate-2032-para-substituir-o-rg-antigo-pelo-novo-cin-e-garantir-os-beneficios/');
insert into tb01_link (titulo,endereco) values ('Novo RG tem um código que não pode ser rasurado: isso invalida o CIN','https://n1n.com.br/noticias-gerais/novo-rg-tem-um-codigo-que-nao-pode-ser-rasurado-isso-invalida-o-cin/');
insert into tb01_link (titulo,endereco) values ('Novo RG em cartão tem um chip e precisa ser solicitado no momento de emitir a CIN','https://n1n.com.br/beneficios/novo-rg-em-cartao-tem-um-chip-e-precisa-ser-solicitado-no-momento-de-emitir-a-cin/');
insert into tb01_link (titulo,endereco) values ('Lista do governo infoma o local exato de agendar para fazer o CIN','https://n1n.com.br/beneficios/lista-do-governo-infoma-o-local-exato-de-agendar-fazer-o-cin/');
insert into tb01_link (titulo,endereco) values ('SAC Bahia atualiza forma de atendimento para fazer o CIN','https://n1n.com.br/noticias-gerais/sac-bahia-atualiza-forma-de-atendimento-para-fazer-o-cin/');
insert into tb01_link (titulo,endereco) values ('CIN em formato cartão já está disponível: veja preço, prazos e como pedir','https://n1n.com.br/beneficios/emissao-da-cin-cartao-esta-liberada-em-varios-estados-veja-preco-prazos-e-como-pedir/');




