create table tb02_usuario (
  id bigint generated by default as identity,
  nome varchar(100) not null,
  username varchar(30) not null unique,
  password varchar(255) not null,
  email varchar(255) not null unique,
  primary key (id)
)
