create table tb03_roles (
  id bigint generated by default as identity,
  nome varchar(100) not null,
  id_usuario bigint not null,
  primary key (id),
  foreign key (id_usuario) references tb02_usuario(id)
)
